######################################################################
#
# File name : Four_Bit_Adder_wave.do
# Created on: Wed Sep 12 23:04:42 -0400 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
