######################################################################
#
# File name : Four_Bit_Adder_simulate.do
# Created on: Wed Sep 12 23:35:07 -0400 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_e/0 +pulse_int_e/0 +pulse_r/0 +pulse_int_r/0 -L xil_defaultlib -L simprims_ver -L secureip -lib xil_defaultlib xil_defaultlib.Four_Bit_Adder xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {Four_Bit_Adder_wave.do}

view wave
view structure
view signals

do {Four_Bit_Adder.udo}

run 1000ns
