######################################################################
#
# File name : Four_Bit_Adder.udo
# Created on: Wed Sep 12 23:04:42 -0400 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
