######################################################################
#
# File name : Seven_Seg_Decoder.udo
# Created on: Tue Sep 25 11:26:02 -0400 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
