######################################################################
#
# File name : Seven_Seg_Decoder_compile.do
# Created on: Tue Sep 25 12:26:45 -0400 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/work
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xil_defaultlib

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xil_defaultlib  \
"../../../../HW3.srcs/sources_1/new/Seven_Seg_Decoder.vhd" \


quit -force

