######################################################################
#
# File name : Task_One_wave.do
# Created on: Wed Sep 19 18:30:35 -0400 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
