######################################################################
#
# File name : Eight_Bit_Magnitude_Comparator.udo
# Created on: Wed Sep 26 22:02:44 -0400 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
