######################################################################
#
# File name : Eight_Bit_Magnitude_Comparator_compile.do
# Created on: Wed Sep 26 19:31:47 -0400 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/work
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xil_defaultlib

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xil_defaultlib  \
"../../../../Lab4.srcs/sources_1/new/Four_Bit_Adder.vhd" \
"../../../../Lab4.srcs/sources_1/new/Four_Bit_Magnitude_Comparator.vhd" \
"../../../../Lab4.srcs/sources_1/new/One_Bit_Adder.vhd" \
"../../../../Lab4.srcs/sources_1/new/One_Bit_Magnitude_Comparator.vhd" \
"../../../../Lab4.srcs/sources_1/new/Six_Way_And.vhd" \
"../../../../Lab4.srcs/sources_1/new/Twos_Complementor.vhd" \
"../../../../Lab4.srcs/sources_1/new/Eight_Bit_Magnitude_Comparator.vhd" \


quit -force

