######################################################################
#
# File name : Eight_Bit_Magnitude_Comparator_wave.do
# Created on: Wed Sep 26 22:14:41 -0400 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
