######################################################################
#
# File name : Seven_Seg_Decoder_wave.do
# Created on: Tue Sep 25 12:29:51 -0400 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
