######################################################################
#
# File name : Four_Bit_Adder.udo
# Created on: Tue Sep 11 11:27:42 -0400 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
