######################################################################
#
# File name : Four_Bit_Adder_simulate.do
# Created on: Tue Sep 11 11:27:42 -0400 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L secureip -lib xil_defaultlib xil_defaultlib.Four_Bit_Adder

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {Four_Bit_Adder_wave.do}

view wave
view structure
view signals

do {Four_Bit_Adder.udo}

run 1000ns
