######################################################################
#
# File name : Four_Bit_Adder_compile.do
# Created on: Tue Sep 11 11:27:41 -0400 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/work
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xil_defaultlib

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xil_defaultlib  \
"../../../../Lab2.srcs/sources_1/new/One_Bit_Adder.vhd" \
"../../../../Lab2.srcs/sources_1/new/Four_Bit_Adder.vhd" \


quit -force

