set_property SRC_FILE_INFO {cfile:C:/Users/Dexter/Documents/ECE4525/Lab3/Lab3.srcs/constrs_1/new/pins_task_two.xdc rfile:../../../Lab3.srcs/constrs_1/new/pins_task_two.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K1    IOSTANDARD LVCMOS33 } [get_ports { A }]; #IO_L23N_T3_35 Sch=jc[1]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F6    IOSTANDARD LVCMOS33 } [get_ports { B }]; #IO_L19N_T3_VREF_35 Sch=jc[2]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J2    IOSTANDARD LVCMOS33 } [get_ports { C }]; #IO_L22N_T3_35 Sch=jc[3]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E7    IOSTANDARD LVCMOS33 } [get_ports { F }]; #IO_L6P_T0_35 Sch=jc[7]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J4    IOSTANDARD LVCMOS33 } [get_ports { F_alpha }]; #IO_L21P_T3_DQS_35 Sch=jc[9]
