######################################################################
#
# File name : Full_Adder.udo
# Created on: Wed Sep 05 19:01:10 -0400 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
