######################################################################
#
# File name : Full_Adder_compile.do
# Created on: Wed Sep 05 19:01:08 -0400 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vcom -64 -93 -work xil_defaultlib  \
"../../../../Lab1.srcs/sources_1/new/Full_Adder.vhd" \


quit -force

