######################################################################
#
# File name : Task_One_wave.do
# Created on: Wed Sep 19 18:27:02 -0400 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
