######################################################################
#
# File name : Task_One_compile.do
# Created on: Wed Sep 19 18:33:24 -0400 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/work
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xil_defaultlib

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vcom -64 -93 -work xil_defaultlib  \
"../../../../Lab3.srcs/sources_1/new/One_Bit_Adder.vhd" \
"../../../../Lab3.srcs/sources_1/new/Two_Line_Mux.vhd" \
"../../../../Lab3.srcs/sources_1/new/Task_One.vhd" \


quit -force

