######################################################################
#
# File name : Task_Two_Part_One_wave.do
# Created on: Wed Sep 19 20:21:19 -0400 2018
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
