######################################################################
#
# File name : State_Machine_compile.do
# Created on: Tue Oct 09 17:21:27 -0400 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/work
D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xil_defaultlib

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlog -64 -incr -work xil_defaultlib  \
"State_Machine_time_impl.v" \


quit -force

