######################################################################
#
# File name : State_Machine_wave.do
# Created on: Tue Oct 09 17:20:06 -0400 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
