######################################################################
#
# File name : State_Machine_simulate.do
# Created on: Tue Oct 09 17:21:28 -0400 2018
#
# Auto generated by Vivado for 'post-implementation' simulation
#
######################################################################
vsim -voptargs="+acc" +transport_int_delays +pulse_e/0 +pulse_int_e/0 +pulse_r/0 +pulse_int_r/0 -L xil_defaultlib -L simprims_ver -L secureip -lib xil_defaultlib xil_defaultlib.State_Machine xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {State_Machine_wave.do}

view wave
view structure
view signals

do {State_Machine.udo}

run 1000ns
